export enum MatchStatus {
  PLANNED = 'PLANNED',
  DONE = 'DONE',
  SETTINGS = 'SETTINGS',
  FIRST_QUARTER = 'FIRST_QUARTER',
  SECOND_QUARTER = 'SECOND_QUARTER',
  THIRD_QUARTER = 'THIRD_QUARTER',
  FOURTH_QUARTER = 'FOURTH_QUARTER',
  OVERTIME = 'OVERTIME'
}
