application:
  title: Basketstats
  creator: Marcin Krysiak
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: 'true'
    show-sql: 'false'
  datasource:
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
    password: ${DATASOURCE_PASSWORD:FVIn2FzYbElP9pr835nt}
    username: ${DATASOURCE_USERNAME:admin}
    url: ${DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=basketstats-reforged;encrypt=true;trustServerCertificate=true;}
#    driver-class-name: org.postgresql.Driver
#    password: postgres
#    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5433/postgres
#    username: postgres
  devtools:
    restart:
      enabled: 'true'
      log-condition-evaluation-delta: 'false'
  servlet:
    multipart:
      max-file-size: 4MB
      enabled: 'true'
      max-request-size: 4MB
      resolve-lazily: 'true'
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  banner:
    location: classpath:banner.txt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://basketstats.eu.auth0.com/
server:
  error:
    include-stacktrace: never
ftp:
  enabled: true
  server:
    host: localhost
    port: 2121
    username: admin
    password: admin
auth0:
  audience: http://localhost:8080/api